# Generated by Django 3.2.8 on 2022-10-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(default='', max_length=50, verbose_name='ip地址')),
                ('port', models.CharField(default='123', max_length=50, verbose_name='端口')),
                ('problem', models.TextField(default='', verbose_name='问题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('description', models.TextField(default='', verbose_name='描述')),
            ],
            options={
                'db_table': 'scans',
            },
        ),
    ]
